name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      env:
        TMP_WORK_DIR: "tmp_dir"
      run: |
        mkdir ${TMP_WORK_DIR}
        cd ${TMP_WORK_DIR}
        git clone https://github.com/eigenteam/eigen-git-mirror.git
        cd eigen-git-mirror
        git checkout 3.3.7
        cd ../../
        sudo mv ${TMP_WORK_DIR}/eigen-git-mirror /opt/
        sudo ln -s /opt/eigen-git-mirror/Eigen/ /usr/local/include/Eigen
        sudo ln -s /opt/eigen-git-mirror/unsupported/ /usr/local/include/unsupported
        cd ${TMP_WORK_DIR}
        git clone https://github.com/boostorg/boost.git
        cd boost
        git checkout boost-1.70.0
        git submodule update --init --recursive
        sudo ./bootstrap.sh
        sudo ./b2 install -j2 --prefix=/usr/local; exit 0
        cd ../../
        rm -rf ${TMP_WORK_DIR}
    - name: make
      run: |
        cd example
        make
    - name: execute
      run: ./example
